version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - development
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1qaz2ws
    container_name: rabbitmq

networks:
  development:
    external: true
    name: development
